# Generated by Django 4.1 on 2024-10-06 21:16

import alumniapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumni",
            fields=[
                ("alumni_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=70)),
                ("dob", models.DateField()),
                ("phno", models.BigIntegerField(unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=200)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        validators=[alumniapp.models.validate_image],
                    ),
                ),
                ("qualification", models.CharField(max_length=50)),
                ("course", models.CharField(max_length=50)),
                ("year_of_passing", models.IntegerField()),
                ("percentage", models.IntegerField()),
                (
                    "certificate",
                    models.FileField(
                        null=True,
                        upload_to="certificates/",
                        validators=[alumniapp.models.validate_pdf],
                    ),
                ),
                ("organization_name", models.CharField(max_length=50)),
                ("doj_month", models.IntegerField()),
                ("doj_year", models.IntegerField()),
                ("job_profile", models.CharField(max_length=50)),
                ("job_location", models.CharField(max_length=50)),
                ("linked_in_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "application_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=70)),
                ("dob", models.DateField()),
                ("phno", models.BigIntegerField(unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=200)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        validators=[alumniapp.models.validate_image],
                    ),
                ),
                ("qualification", models.CharField(max_length=50)),
                ("course", models.CharField(max_length=50)),
                ("year_of_passing", models.IntegerField()),
                ("percentage", models.IntegerField()),
                (
                    "certificate",
                    models.FileField(
                        null=True,
                        upload_to="certificates/",
                        validators=[alumniapp.models.validate_pdf],
                    ),
                ),
                ("organization_name", models.CharField(max_length=50)),
                ("doj_month", models.IntegerField()),
                ("doj_year", models.IntegerField()),
                ("job_profile", models.CharField(max_length=50)),
                ("job_location", models.CharField(max_length=50)),
                ("linked_in_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Coordinator",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fullname", models.CharField(max_length=70)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ("otp", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Posts",
            fields=[
                ("post_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("posted_on", models.DateField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=3000)),
                ("link1", models.URLField(null=True)),
                ("link2", models.URLField(null=True)),
                ("link3", models.URLField(null=True)),
            ],
        ),
    ]
