# Generated by Django 5.0.4 on 2024-10-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('posted_on', models.DateField()),
                ('is_new', models.CharField(max_length=3)),
                ('event', models.FileField(null=True, upload_to='events/')),
            ],
        ),
    ]
